### ISSUE TITLE
OLa插件乱码问题！！！

### ISSUE THREAD

**Issue by deepblueye** [d3ckx1/OLa#3]
载入OLa插件，当前cs版本是4.9.1版本，发现菜单显示全部是乱码，希望作者帮忙修复一下乱码问题。
<img width="196" alt="image" src="https://github.com/d3ckx1/OLa/assets/15513999/95ff967a-c0b6-4d41-85cd-e5b40e730aab">

**Comment by d3ckx1** [comment]
解决方法：打开所有.cna文件，重新编码保存为GBK格式即可。

**Comment by deepblueye** [comment]
用什么IDE打开？

**Comment by deepblueye** [comment]
照着你说的方法还是不行，还是乱码，依旧乱码！？
